name: CI Pipeline

on:
  push:
    branches:
      - main, 
      - stage
  pull_request:
    branches:
      - main,
      - stage

jobs:
  run-fastapi-server:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python (FastAPI)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r bookstore/requirements.txt

      - name: Start FastAPI Server
        run: |
          nohup uvicorn bookstore.main:app --host 127.0.0.1 --port 8000 &
        shell: bash

  tests:
    runs-on: windows-latest
    needs: run-fastapi-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r bookstore/requirements.txt

      - name: Run Unit Tests with pytest and report code coverage
        run: |
          pip install pytest pytest-cov
          python -m pytest --cov=bookstore

      - name: Run Integration Tests with pytest
        run: |
          pip install pytest pytest-xdist
          python -m pytest -s "TestCases/IntegrationTests" 

  upload-coverage-report:
    needs: tests
    runs-on: windows-latest
    steps:
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
